version: 2.1
jobs:
  code-quality:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run tests and linting
          command: |
            npm test
            npm run lint

  eas-preview-build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Trigger build
          command: npx eas-cli build --platform all --non-interactive --no-wait

workflows:
  version: 2
  code-quality:
    jobs:
      - code-quality

  build-app:
    jobs:
      - eas-preview-build
