version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Run linting
          command: npm run lint

      - run:
          name: Build Expo development app
          command: npm run build:expo

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
