version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:lts

    working_directory: ~/plantify-app

jobs:
  code-quality:
    executor: default

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run tests and linting
          command: |
            npm test
            npm run lint

  eas-preview-build:
    executor: default

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Trigger build
          command: npx eas-cli build --profile preview --platform all --non-interactive --no-wait
          
  eas-development-build:
    executor: default

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Trigger build
          command: |
            npx eas-cli build --profile development --platform android --non-interactive --no-wait
            npx eas-cli build --profile development-simulator --platform ios --non-interactive --no-wait

workflows:
  version: 2
  code-quality:
    jobs:
      - code-quality:
          filters:
            branches:
              only:
                - /^PLAN-.*$/

  build-app:
    jobs:
      - code-quality:
          filters:
              branches:
                only:
                  - main

      - eas-preview-build:
          requires:
            - code-quality
          filters:
            branches:
              only:
                - main

      - eas-development-build:
          requires:
            - code-quality
          filters:
            branches:
              only:
                - /^PLAN-.*$/          
          hold: true
